services:

  db:
    image: postgres:17
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-postgres} -d ${POSTGRES_DB:-app}" ]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s
    volumes:
      - app-db-data:/var/lib/postgresql/data/pgdata
    env_file:
      - .env.production
    environment:
      - PGDATA=/var/lib/postgresql/data/pgdata
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-changethis}
      - POSTGRES_USER=${POSTGRES_USER:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-app}

  prestart:
    image: '${DOCKER_IMAGE_BACKEND:-capri-backend}:latest'
    build:
      context: ./backend
    depends_on:
      db:
        condition: service_healthy
        restart: true
    command: bash scripts/prestart.sh
    env_file:
      - .env.production
    environment:
      - POSTGRES_SERVER=db

  backend:
    image: '${DOCKER_IMAGE_BACKEND:-capri-backend}:latest'
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
        restart: true
      prestart:
        condition: service_completed_successfully
    env_file:
      - .env.production
    environment:
      - POSTGRES_SERVER=db

  frontend:
    image: '${DOCKER_IMAGE_FRONTEND:-capri-frontend}:latest'
    restart: always
    ports:
      - "3000:80"
    build:
      context: ./frontend
      args:
        - VITE_API_URL=http://capridoradal.online:8000
        - NODE_ENV=production

volumes:
  app-db-data:
