// This file is auto-generated by @hey-api/openapi-ts

export const Body_login_login_access_tokenSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: '^password$'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            format: 'password',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            format: 'password',
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_login-login_access_token'
} as const;

export const BookingCreateSchema = {
    properties: {
        check_in: {
            type: 'string',
            format: 'date',
            title: 'Check In'
        },
        check_out: {
            type: 'string',
            format: 'date',
            title: 'Check Out'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        room_id: {
            type: 'integer',
            title: 'Room Id'
        }
    },
    type: 'object',
    required: ['check_in', 'check_out', 'user_id', 'room_id'],
    title: 'BookingCreate',
    description: 'Schema para crear una reserva.'
} as const;

export const BookingReadSchema = {
    properties: {
        check_in: {
            type: 'string',
            format: 'date',
            title: 'Check In'
        },
        check_out: {
            type: 'string',
            format: 'date',
            title: 'Check Out'
        },
        status: {
            '$ref': '#/components/schemas/BookingStatus',
            default: 'pending'
        },
        id: {
            type: 'string',
            format: 'uuid',
            title: 'Id'
        },
        user_id: {
            type: 'integer',
            title: 'User Id'
        },
        room_id: {
            type: 'integer',
            title: 'Room Id'
        }
    },
    type: 'object',
    required: ['check_in', 'check_out', 'id', 'user_id', 'room_id'],
    title: 'BookingRead'
} as const;

export const BookingStatusSchema = {
    type: 'string',
    enum: ['pending', 'confirmed', 'cancelled', 'no_show', 'checked_in', 'checked_out'],
    title: 'BookingStatus',
    description: 'Estados posibles de una reserva.'
} as const;

export const BookingUpdateSchema = {
    properties: {
        check_in: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Check In'
        },
        check_out: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Check Out'
        },
        room_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Room Id'
        },
        status: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/BookingStatus'
                },
                {
                    type: 'null'
                }
            ]
        }
    },
    type: 'object',
    title: 'BookingUpdate',
    description: 'Schema para actualizar una reserva.'
} as const;

export const DocumentTypeSchema = {
    type: 'string',
    enum: ['Cédula', 'Tarjeta de identidad', 'Cédula de extranjería', 'Pasaporte'],
    title: 'DocumentType'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const MessageSchema = {
    properties: {
        message: {
            type: 'string',
            title: 'Message'
        }
    },
    type: 'object',
    required: ['message'],
    title: 'Message'
} as const;

export const NewPasswordSchema = {
    properties: {
        token: {
            type: 'string',
            title: 'Token'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['token', 'new_password'],
    title: 'NewPassword'
} as const;

export const PrivateUserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            title: 'Email'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        name: {
            type: 'string',
            title: 'Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        document_type: {
            type: 'string',
            title: 'Document Type'
        },
        document_number: {
            type: 'string',
            title: 'Document Number'
        },
        phone_number: {
            type: 'string',
            title: 'Phone Number'
        },
        is_verified: {
            type: 'boolean',
            title: 'Is Verified',
            default: false
        }
    },
    type: 'object',
    required: ['email', 'password', 'name', 'last_name', 'document_type', 'document_number', 'phone_number'],
    title: 'PrivateUserCreate'
} as const;

export const RoomCreateSchema = {
    properties: {
        room_number: {
            type: 'integer',
            minimum: 1,
            title: 'Room Number'
        },
        is_available: {
            type: 'boolean',
            title: 'Is Available',
            default: true
        },
        room_type_id: {
            type: 'integer',
            title: 'Room Type Id'
        }
    },
    type: 'object',
    required: ['room_number', 'room_type_id'],
    title: 'RoomCreate'
} as const;

export const RoomReadSchema = {
    properties: {
        room_number: {
            type: 'integer',
            minimum: 1,
            title: 'Room Number'
        },
        is_available: {
            type: 'boolean',
            title: 'Is Available',
            default: true
        },
        room_type_id: {
            type: 'integer',
            title: 'Room Type Id'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['room_number', 'room_type_id', 'id'],
    title: 'RoomRead'
} as const;

export const RoomTypeCreateSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 500,
            title: 'Description'
        },
        capacity: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Capacity'
        },
        amenities: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Amenities'
        },
        base_price: {
            type: 'number',
            minimum: 0,
            title: 'Base Price'
        }
    },
    type: 'object',
    required: ['name', 'description', 'capacity', 'base_price'],
    title: 'RoomTypeCreate'
} as const;

export const RoomTypeReadSchema = {
    properties: {
        name: {
            type: 'string',
            maxLength: 100,
            title: 'Name'
        },
        description: {
            type: 'string',
            maxLength: 500,
            title: 'Description'
        },
        capacity: {
            type: 'integer',
            maximum: 50,
            minimum: 1,
            title: 'Capacity'
        },
        amenities: {
            items: {
                type: 'string'
            },
            type: 'array',
            title: 'Amenities'
        },
        base_price: {
            type: 'number',
            minimum: 0,
            title: 'Base Price'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'description', 'capacity', 'base_price', 'id'],
    title: 'RoomTypeRead'
} as const;

export const TokenSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'bearer'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'Token'
} as const;

export const UpdatePasswordSchema = {
    properties: {
        current_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Current Password'
        },
        new_password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'New Password'
        }
    },
    type: 'object',
    required: ['current_password', 'new_password'],
    title: 'UpdatePassword'
} as const;

export const UserCreateSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        last_name: {
            type: 'string',
            maxLength: 255,
            title: 'Last Name'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType'
        },
        document_number: {
            type: 'string',
            maxLength: 50,
            title: 'Document Number'
        },
        phone_number: {
            type: 'string',
            maxLength: 10,
            minLength: 10,
            title: 'Phone Number'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        }
    },
    type: 'object',
    required: ['email', 'name', 'last_name', 'document_type', 'document_number', 'phone_number', 'password'],
    title: 'UserCreate'
} as const;

export const UserPublicSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active',
            default: true
        },
        is_superuser: {
            type: 'boolean',
            title: 'Is Superuser',
            default: false
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        last_name: {
            type: 'string',
            maxLength: 255,
            title: 'Last Name'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType'
        },
        document_number: {
            type: 'string',
            maxLength: 50,
            title: 'Document Number'
        },
        phone_number: {
            type: 'string',
            maxLength: 10,
            minLength: 10,
            title: 'Phone Number'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['email', 'name', 'last_name', 'document_type', 'document_number', 'phone_number', 'id'],
    title: 'UserPublic'
} as const;

export const UserRegisterSchema = {
    properties: {
        email: {
            type: 'string',
            maxLength: 255,
            format: 'email',
            title: 'Email'
        },
        password: {
            type: 'string',
            maxLength: 40,
            minLength: 8,
            title: 'Password'
        },
        name: {
            type: 'string',
            maxLength: 255,
            title: 'Name'
        },
        last_name: {
            type: 'string',
            maxLength: 255,
            title: 'Last Name'
        },
        document_type: {
            '$ref': '#/components/schemas/DocumentType'
        },
        document_number: {
            type: 'string',
            maxLength: 50,
            title: 'Document Number'
        },
        phone_number: {
            type: 'string',
            maxLength: 10,
            minLength: 10,
            title: 'Phone Number'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        }
    },
    type: 'object',
    required: ['email', 'password', 'name', 'last_name', 'document_type', 'document_number', 'phone_number'],
    title: 'UserRegister'
} as const;

export const UserUpdateSchema = {
    properties: {
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        },
        is_superuser: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Superuser'
        },
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        document_type: {
            anyOf: [
                {
                    '$ref': '#/components/schemas/DocumentType'
                },
                {
                    type: 'null'
                }
            ]
        },
        document_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 50
                },
                {
                    type: 'null'
                }
            ],
            title: 'Document Number'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10,
                    minLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        },
        password: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 40,
                    minLength: 8
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        }
    },
    type: 'object',
    title: 'UserUpdate'
} as const;

export const UserUpdateMeSchema = {
    properties: {
        name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Name'
        },
        last_name: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Name'
        },
        email: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 255,
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Email'
        },
        phone_number: {
            anyOf: [
                {
                    type: 'string',
                    maxLength: 10,
                    minLength: 10
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone Number'
        },
        birth_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birth Date'
        }
    },
    type: 'object',
    title: 'UserUpdateMe'
} as const;

export const UsersPublicSchema = {
    properties: {
        data: {
            items: {
                '$ref': '#/components/schemas/UserPublic'
            },
            type: 'array',
            title: 'Data'
        },
        count: {
            type: 'integer',
            title: 'Count'
        }
    },
    type: 'object',
    required: ['data', 'count'],
    title: 'UsersPublic'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;