// This file is auto-generated by @hey-api/openapi-ts

export type Body_login_login_access_token = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

/**
 * Schema para crear una reserva.
 */
export type BookingCreate = {
    check_in: string;
    check_out: string;
    user_id: number;
    room_id: number;
};

export type BookingRead = {
    check_in: string;
    check_out: string;
    status?: BookingStatus;
    id: string;
    user_id: number;
    room_id: number;
};

/**
 * Estados posibles de una reserva.
 */
export type BookingStatus = 'pending' | 'confirmed' | 'cancelled' | 'no_show' | 'checked_in' | 'checked_out';

/**
 * Schema para actualizar una reserva.
 */
export type BookingUpdate = {
    check_in?: (string | null);
    check_out?: (string | null);
    room_id?: (number | null);
    status?: (BookingStatus | null);
};

export type DocumentType = 'Cédula' | 'Tarjeta de identidad' | 'Cédula de extranjería' | 'Pasaporte';

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type Message = {
    message: string;
};

export type NewPassword = {
    token: string;
    new_password: string;
};

export type PrivateUserCreate = {
    email: string;
    password: string;
    name: string;
    last_name: string;
    document_type: string;
    document_number: string;
    phone_number: string;
    is_verified?: boolean;
};

export type RoomCreate = {
    room_number: number;
    is_available?: boolean;
    room_type_id: number;
};

export type RoomRead = {
    room_number: number;
    is_available?: boolean;
    room_type_id: number;
    id: number;
};

export type RoomTypeCreate = {
    name: string;
    description: string;
    capacity: number;
    amenities?: Array<(string)>;
    base_price: number;
};

export type RoomTypeRead = {
    name: string;
    description: string;
    capacity: number;
    amenities?: Array<(string)>;
    base_price: number;
    id: number;
};

export type Token = {
    access_token: string;
    token_type?: string;
};

export type UpdatePassword = {
    current_password: string;
    new_password: string;
};

export type UserCreate = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    name: string;
    last_name: string;
    document_type: DocumentType;
    document_number: string;
    phone_number: string;
    birth_date?: (string | null);
    password: string;
};

export type UserPublic = {
    email: string;
    is_active?: boolean;
    is_superuser?: boolean;
    name: string;
    last_name: string;
    document_type: DocumentType;
    document_number: string;
    phone_number: string;
    birth_date?: (string | null);
    id: number;
};

export type UserRegister = {
    email: string;
    password: string;
    name: string;
    last_name: string;
    document_type: DocumentType;
    document_number: string;
    phone_number: string;
    birth_date?: (string | null);
};

export type UsersPublic = {
    data: Array<UserPublic>;
    count: number;
};

export type UserUpdate = {
    email?: (string | null);
    is_active?: (boolean | null);
    is_superuser?: (boolean | null);
    name?: (string | null);
    last_name?: (string | null);
    document_type?: (DocumentType | null);
    document_number?: (string | null);
    phone_number?: (string | null);
    birth_date?: (string | null);
    password?: (string | null);
};

export type UserUpdateMe = {
    name?: (string | null);
    last_name?: (string | null);
    email?: (string | null);
    phone_number?: (string | null);
    birth_date?: (string | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type BookingsCreateBookingData = {
    requestBody: BookingCreate;
};

export type BookingsCreateBookingResponse = (BookingRead);

export type BookingsReadBookingsData = {
    limit?: number;
    skip?: number;
};

export type BookingsReadBookingsResponse = (Array<BookingRead>);

export type BookingsReadBookingData = {
    bookingId: string;
};

export type BookingsReadBookingResponse = (BookingRead);

export type BookingsUpdateBookingData = {
    bookingId: string;
    requestBody: BookingUpdate;
};

export type BookingsUpdateBookingResponse = (BookingRead);

export type BookingsDeleteBookingData = {
    bookingId: string;
};

export type BookingsDeleteBookingResponse = (unknown);

export type BookingsConfirmBookingData = {
    bookingId: string;
};

export type BookingsConfirmBookingResponse = (BookingRead);

export type BookingsCancelBookingData = {
    bookingId: string;
};

export type BookingsCancelBookingResponse = (BookingRead);

export type BookingsCheckInBookingData = {
    bookingId: string;
};

export type BookingsCheckInBookingResponse = (BookingRead);

export type BookingsCheckOutBookingData = {
    bookingId: string;
};

export type BookingsCheckOutBookingResponse = (BookingRead);

export type BookingsMarkBookingNoShowData = {
    bookingId: string;
};

export type BookingsMarkBookingNoShowResponse = (BookingRead);

export type LoginLoginAccessTokenData = {
    formData: Body_login_login_access_token;
};

export type LoginLoginAccessTokenResponse = (Token);

export type LoginTestTokenResponse = (UserPublic);

export type LoginRecoverPasswordData = {
    email: string;
};

export type LoginRecoverPasswordResponse = (Message);

export type LoginResetPasswordData = {
    requestBody: NewPassword;
};

export type LoginResetPasswordResponse = (Message);

export type LoginRecoverPasswordHtmlContentData = {
    email: string;
};

export type LoginRecoverPasswordHtmlContentResponse = (string);

export type PrivateCreateUserData = {
    requestBody: PrivateUserCreate;
};

export type PrivateCreateUserResponse = (UserPublic);

export type RoomsCreateRoomData = {
    requestBody: RoomCreate;
};

export type RoomsCreateRoomResponse = (RoomRead);

export type RoomsReadRoomsData = {
    limit?: number;
    skip?: number;
};

export type RoomsReadRoomsResponse = (Array<RoomRead>);

export type RoomsCheckAvailabilityData = {
    /**
     * Fecha de entrada
     */
    checkIn: string;
    /**
     * Fecha de salida
     */
    checkOut: string;
    /**
     * Filtrar por tipo de habitación
     */
    roomTypeId?: (number | null);
};

export type RoomsCheckAvailabilityResponse = (Array<RoomRead>);

export type RoomsReadRoomData = {
    roomId: number;
};

export type RoomsReadRoomResponse = (RoomRead);

export type RoomsUpdateRoomData = {
    requestBody: RoomCreate;
    roomId: number;
};

export type RoomsUpdateRoomResponse = (RoomRead);

export type RoomsDeleteRoomData = {
    roomId: number;
};

export type RoomsDeleteRoomResponse = (unknown);

export type RoomTypesCreateRoomTypeData = {
    requestBody: RoomTypeCreate;
};

export type RoomTypesCreateRoomTypeResponse = (RoomTypeRead);

export type RoomTypesReadRoomTypesData = {
    limit?: number;
    skip?: number;
};

export type RoomTypesReadRoomTypesResponse = (Array<RoomTypeRead>);

export type RoomTypesReadRoomTypeData = {
    roomTypeId: number;
};

export type RoomTypesReadRoomTypeResponse = (RoomTypeRead);

export type RoomTypesUpdateRoomTypeData = {
    requestBody: RoomTypeCreate;
    roomTypeId: number;
};

export type RoomTypesUpdateRoomTypeResponse = (RoomTypeRead);

export type RoomTypesDeleteRoomTypeData = {
    roomTypeId: number;
};

export type RoomTypesDeleteRoomTypeResponse = (unknown);

export type UsersReadUsersData = {
    limit?: number;
    skip?: number;
    q?: string;
};

export type UsersReadUsersResponse = (UsersPublic);

export type UsersCreateUserData = {
    requestBody: UserCreate;
};

export type UsersCreateUserResponse = (UserPublic);

export type UsersReadUserMeResponse = (UserPublic);

export type UsersDeleteUserMeResponse = (Message);

export type UsersUpdateUserMeData = {
    requestBody: UserUpdateMe;
};

export type UsersUpdateUserMeResponse = (UserPublic);

export type UsersUpdatePasswordMeData = {
    requestBody: UpdatePassword;
};

export type UsersUpdatePasswordMeResponse = (Message);

export type UsersRegisterUserData = {
    requestBody: UserRegister;
};

export type UsersRegisterUserResponse = (UserPublic);

export type UsersReadUserByIdData = {
    userId: number;
};

export type UsersReadUserByIdResponse = (UserPublic);

export type UsersUpdateUserData = {
    requestBody: UserUpdate;
    userId: number;
};

export type UsersUpdateUserResponse = (UserPublic);

export type UsersDeleteUserData = {
    userId: number;
};

export type UsersDeleteUserResponse = (Message);

export type UsersSearchUserByDocumentData = {
    documentNumber: string;
};

export type UsersSearchUserByDocumentResponse = (UserPublic);

export type UtilsTestEmailData = {
    emailTo: string;
};

export type UtilsTestEmailResponse = (Message);

export type UtilsHealthCheckResponse = (boolean);